"""
# API Configuration
openai:
  api_key: "your-openai-api-key-here"
  model: "gpt-4"
  temperature: 0.7
  max_tokens: 2000

# Search Configuration
search:
  engine: "duckduckgo"  # or "serpapi", "google"
  max_results: 5

# Report Configuration
report:
  default_format: "pdf"  # pdf, docx, html
  include_charts: true
  include_references: true
  sections:
    - Executive Summary
    - Key Findings
    - Data Analysis
    - Visualizations
    - Recommendations
    - References

# Chart Configuration
charts:
  style: "seaborn"
  default_type: "bar"
  color_palette: "viridis"
"""